---
# tasks file for nginx
- name: Debug
  debug:
    msg: "Hello"

- name: Install Packages
  apt:
    name:
      - python3
      - software-properties-common
      - php8.1-fpm
      - php8.1-common
      - libapache2-mod-php
      - php-cgi
      - nginx 
    state: present
    update_cache: yes

- name: Copy config
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: nginx.conf
      dest: /nginx/nginx.conf
    - src: default.conf
      dest: /etc/nginx/sites-enabled/default
    - src: index.php
      dest: /var/www/html/index.php

- name: Nginx Restart
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - nginx
    - php8.1-fpm
